[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "quadruped_poser"
version = "1.0.0"
description = "VAE-based pose prior for quadruped body models."
authors = [{ name = "Dennis Perrett"}]
dependencies = [
    "pyglet<2.0",
    "torch",
    "tqdm",
    "trimesh",
    "varen",
]

[tool.setuptools.packages.find]
where = ["."]
